version: '3.8'

services:
  app:
    build: .
    container_name: instalite-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - xml-network

  db:
    image: 'postgres:latest'
    container_name: instalite-db
    environment:
      - 'POSTGRES_DB=instadatabase'
      - 'POSTGRES_PASSWORD=secretinsta'
      - 'POSTGRES_USER=userinsta'
    ports:
      - "5435:5432"
    networks:
      - xml-network


networks:
  xml-network: