spring.application.name=InstaLite

# ===============================
# DATABASE POSTGRES
# ===============================

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.springframework.boot.orm.jpa.SpringJtaPlatform
spring.jpa.hibernate.ddl-auto=update

# ===============================
# DATABASE POSTGRES DOCKER
# ===============================

spring.datasource.url=jdbc:postgresql://instalite-db:5432/instadatabase
spring.datasource.username=userinsta
spring.datasource.password=secretinsta

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true